-- Run this file once in the Supabase SQL Editor.
-- It creates database-backed notifications for interests and messages.

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  type text not null check (type in ('like', 'message', 'accepted', 'connection', 'profile_complete')),
  title text not null,
  subtitle text,
  href text,
  source_key text unique,
  read_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists notifications_user_created_idx
  on public.notifications (user_id, created_at desc);
create index if not exists notifications_user_unread_idx
  on public.notifications (user_id, read_at) where read_at is null;

alter table public.notifications enable row level security;
revoke all on table public.notifications from anon, authenticated;
grant select, update (read_at), delete on table public.notifications to authenticated;

drop policy if exists "Users can read their notifications" on public.notifications;
drop policy if exists "Users can mark their notifications read" on public.notifications;
drop policy if exists "Users can delete their notifications" on public.notifications;
create policy "Users can read their notifications"
  on public.notifications for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "Users can mark their notifications read"
  on public.notifications for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can delete their notifications"
  on public.notifications for delete to authenticated
  using ((select auth.uid()) = user_id);

create or replace function public.notify_profile_like()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.notifications (user_id, actor_id, type, title, subtitle, href, source_key)
    values (
      new.liked_id,
      new.liker_id,
      'like',
      'liked your profile.',
      'View their profile and respond to the interest.',
      '/requests?tab=received',
      'like:' || new.liker_id::text || ':' || new.liked_id::text
    ) on conflict (source_key) do nothing;
  elsif tg_op = 'UPDATE' and new.status = 'accepted' and old.status is distinct from new.status then
    insert into public.notifications (user_id, actor_id, type, title, subtitle, href, source_key)
    values (
      new.liker_id,
      new.liked_id,
      'accepted',
      'accepted your interest.',
      'You can start a conversation now.',
      '/messages',
      'accepted:' || new.liker_id::text || ':' || new.liked_id::text
    ) on conflict (source_key) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists profile_likes_create_notification on public.profile_likes;
create trigger profile_likes_create_notification
after insert or update of status on public.profile_likes
for each row execute procedure public.notify_profile_like();

create or replace function public.notify_new_message()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  recipient_id uuid;
begin
  recipient_id := case
    when new.sender_id = new.interest_liker_id then new.interest_liked_id
    else new.interest_liker_id
  end;
  insert into public.notifications (user_id, actor_id, type, title, subtitle, href, source_key)
  values (
    recipient_id,
    new.sender_id,
    'message',
    'sent you a message.',
    left(new.body, 160),
    '/messages',
    'message:' || new.id::text
  ) on conflict (source_key) do nothing;
  return new;
end;
$$;

drop trigger if exists messages_create_notification on public.messages;
create trigger messages_create_notification
after insert on public.messages
for each row execute procedure public.notify_new_message();

-- Backfill notifications from existing application activity.
insert into public.notifications (user_id, actor_id, type, title, subtitle, href, source_key, created_at)
select
  liked_id,
  liker_id,
  'like',
  'liked your profile.',
  'View their profile and respond to the interest.',
  '/requests?tab=received',
  'like:' || liker_id::text || ':' || liked_id::text,
  created_at
from public.profile_likes
on conflict (source_key) do nothing;

insert into public.notifications (user_id, actor_id, type, title, subtitle, href, source_key, created_at)
select
  liker_id,
  liked_id,
  'accepted',
  'accepted your interest.',
  'You can start a conversation now.',
  '/messages',
  'accepted:' || liker_id::text || ':' || liked_id::text,
  coalesce(responded_at, created_at)
from public.profile_likes
where status = 'accepted'
on conflict (source_key) do nothing;

insert into public.notifications (user_id, actor_id, type, title, subtitle, href, source_key, read_at, created_at)
select
  case when sender_id = interest_liker_id then interest_liked_id else interest_liker_id end,
  sender_id,
  'message',
  'sent you a message.',
  left(body, 160),
  '/messages',
  'message:' || id::text,
  read_at,
  created_at
from public.messages
on conflict (source_key) do nothing;

do $$ begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then null;
end $$;
