"use client";

import { ProfileImage } from "@/components/ui/ProfileImage";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { BadgeCheck, Bell, CheckCheck, ArrowLeft, ChevronRight, Info, MapPin, Mic, Search, Send, ShieldCheck, SlidersHorizontal, Sparkles, SquarePen } from "lucide-react";
import { type ChatMessage, type Conversation, type ConversationFilter } from "@/data/messages";
import { createClient } from "@/lib/supabase/client";
import { AppSidebar } from "@/components/layout/AppSidebar";
import { Brand } from "@/components/auth/Brand";

export function MessagesClient({ initialConversations, initialMessages, currentUserId, viewerName, avatarUrl, readReceipts }: { initialConversations: Conversation[]; initialMessages: ChatMessage[]; currentUserId: string; viewerName: string; avatarUrl: string; readReceipts: boolean; }) {
  const router = useRouter(); const [filter, setFilter] = useState<ConversationFilter>("all"); const [query, setQuery] = useState(""); const [conversations, setConversations] = useState(initialConversations); const [selectedId, setSelectedId] = useState(initialConversations[0]?.id ?? ""); const [chat, setChat] = useState<ChatMessage[]>(initialMessages); const [draft, setDraft] = useState(""); const [notice, setNotice] = useState(""); const [mobileChatOpen, setMobileChatOpen] = useState(false); const [detailsOpen, setDetailsOpen] = useState(false);
  const visible = useMemo(() => conversations.filter((item) => { const matches = `${item.name} ${item.preview} ${item.profession}`.toLowerCase().includes(query.toLowerCase()); const matchesFilter = filter === "all" || (filter === "unread" && item.unread > 0) || (filter === "favourites" && item.favourite === true); return matches && matchesFilter; }), [conversations, filter, query]);
  const selected = conversations.find((item) => item.id === selectedId) ?? conversations[0]; const unread = conversations.reduce((sum, item) => sum + item.unread, 0); const selectedMessages = selected ? chat.filter((message) => message.conversationId === selected.id) : [];
  useEffect(() => { setConversations(initialConversations); setChat(initialMessages); setSelectedId((current) => initialConversations.some((item) => item.id === current) ? current : (initialConversations[0]?.id ?? "")); }, [initialConversations, initialMessages]);
  useEffect(() => { const supabase = createClient(); const channel = supabase.channel(`messages:${currentUserId}`).on("postgres_changes", { event: "INSERT", schema: "public", table: "messages" }, (payload) => { const row = payload.new as { id:number; interest_liker_id:string; interest_liked_id:string; sender_id:string; body:string; read_at:string|null; created_at:string }; const id=`${row.interest_liker_id}:${row.interest_liked_id}`; const message:ChatMessage={id:String(row.id),conversationId:id,sender:row.sender_id===currentUserId?"me":"them",senderId:row.sender_id,text:row.body,time:formatTime(row.created_at),createdAt:row.created_at,seen:Boolean(row.read_at)}; setChat(items=>items.some(i=>i.id===message.id)?items:[...items,message]); setConversations(items=>items.map(c=>c.id===id?{...c,preview:row.body,time:formatTime(row.created_at),unread:row.sender_id!==currentUserId?c.unread+1:c.unread}:c)); }).on("postgres_changes",{event:"UPDATE",schema:"public",table:"profile_likes"},payload=>{const row=payload.new as {liker_id:string;liked_id:string;status:string};if(row.status==="accepted"&&(row.liker_id===currentUserId||row.liked_id===currentUserId))router.refresh();}).on("postgres_changes",{event:"*",schema:"public",table:"profile_shortlists",filter:`user_id=eq.${currentUserId}`},()=>router.refresh()).subscribe(); return()=>{void supabase.removeChannel(channel);};},[currentUserId,router]);
  useEffect(()=>{if(!readReceipts||!selected||selected.unread===0)return;const supabase=createClient();void supabase.from("messages").update({read_at:new Date().toISOString()}).eq("interest_liker_id",selected.interestLikerId).eq("interest_liked_id",selected.interestLikedId).neq("sender_id",currentUserId).is("read_at",null).then(({error})=>{if(!error)setConversations(items=>items.map(item=>item.id===selected.id?{...item,unread:0}:item));});},[currentUserId,readReceipts,selected]);
  async function sendMessage(){const text=draft.trim();if(!text||!selected)return;setNotice("");setDraft("");const supabase=createClient();const{data,error}=await supabase.from("messages").insert({interest_liker_id:selected.interestLikerId,interest_liked_id:selected.interestLikedId,sender_id:currentUserId,body:text}).select("id, interest_liker_id, interest_liked_id, sender_id, body, read_at, created_at").single();if(error){setDraft(text);setNotice(error.code==="42501"?"You can message only after an interest is accepted.":"Message could not be sent. Please try again.");return;}const message:ChatMessage={id:String(data.id),conversationId:selected.id,sender:"me",senderId:currentUserId,text:data.body,time:formatTime(data.created_at),createdAt:data.created_at,seen:Boolean(data.read_at)};setChat(items=>items.some(i=>i.id===message.id)?items:[...items,message]);setConversations(items=>items.map(item=>item.id===selected.id?{...item,preview:message.text,time:message.time}:item));}
  return <div className="h-dvh overflow-hidden bg-white"><div className="app-shell"><AppSidebar active="Messages" hideMobileNavigation={mobileChatOpen}/><div className="grid min-w-0 flex-1 md:grid-cols-[390px_minmax(0,1fr)] xl:grid-cols-[430px_minmax(0,1fr)]"><ConversationPanel filter={filter} setFilter={setFilter} query={query} setQuery={setQuery} visible={visible} selectedId={selectedId} setSelectedId={id=>{setSelectedId(id);setMobileChatOpen(true);}} mobileChatOpen={mobileChatOpen} unread={unread} viewerName={viewerName}/>{selected?<ChatPanel selected={selected} chat={selectedMessages} draft={draft} setDraft={setDraft} sendMessage={sendMessage} notice={notice} mobileOpen={mobileChatOpen} onBack={()=>setMobileChatOpen(false)} onDetails={()=>setDetailsOpen(o=>!o)}/>:<EmptyChat/>}{selected&&detailsOpen?<ProfileDetails conversation={selected} onClose={()=>setDetailsOpen(false)}/>:null}</div></div></div>;
}
function ConversationPanel({filter,setFilter,query,setQuery,visible,selectedId,setSelectedId,mobileChatOpen,unread,viewerName}:{filter:ConversationFilter;setFilter:(v:ConversationFilter)=>void;query:string;setQuery:(v:string)=>void;visible:Conversation[];selectedId:string;setSelectedId:(id:string)=>void;mobileChatOpen:boolean;unread:number;viewerName:string;}){return <section className={`relative min-w-0 overflow-hidden border-r border-[#dbdfe4] bg-white max-md:bg-[#fbfcff] ${mobileChatOpen?"max-md:hidden":""}`}><div className="relative px-7 pb-4 pt-7 max-md:px-4 max-md:pb-3 max-md:pt-5"><div className="hidden items-center justify-between md:flex"><h1 className="truncate text-[20px] font-bold">{viewerName}</h1><button aria-label="New message"><SquarePen size={24}/></button></div><div className="flex items-center justify-between md:hidden"><Brand compact/><Link href="/notifications" aria-label="Notifications" className="relative grid size-11 place-items-center rounded-[15px] bg-white/90 shadow-[0_7px_22px_rgba(15,20,25,.07)]"><Bell size={22}/></Link></div><label className="mt-5 flex h-12 items-center gap-3 rounded-full bg-[#f1f3f5] px-5 text-[#667781] max-md:bg-white/95 max-md:shadow-[0_8px_28px_rgba(63,38,110,.07)]"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} className="min-w-0 flex-1 bg-transparent text-[15px] outline-none placeholder:text-[#777c91]" placeholder="Search messages"/><SlidersHorizontal size={18} className="md:hidden"/></label><div className="mt-4 flex gap-2 overflow-x-auto pb-1 md:hidden"><FilterPill active={filter==="all"} onClick={()=>setFilter("all")}>All</FilterPill><FilterPill active={filter==="unread"} onClick={()=>setFilter("unread")}>Unread{unread?<span className="ml-1">{unread}</span>:null}</FilterPill><FilterPill active={filter==="favourites"} onClick={()=>setFilter("favourites")}>Favourites</FilterPill></div></div><div className="relative h-[calc(100dvh-190px)] overflow-y-auto px-3 pb-28">{visible.length?visible.map(item=><ConversationRow key={item.id} item={item} active={item.id===selectedId} onClick={()=>setSelectedId(item.id)}/>):<p className="p-8 text-center text-sm text-[#777c91]">{filter==="favourites"?"No shortlisted conversations yet.":"No messages found."}</p>}</div></section>}
function ConversationRow({item,active,onClick}:{item:Conversation;active:boolean;onClick:()=>void;}){return <button onClick={onClick} className={`relative mb-3 flex min-h-[112px] w-full items-center gap-4 rounded-[24px] px-4 py-3.5 text-left max-md:bg-white ${active?"md:bg-[#f1f3f5]":""}`}><span className="relative size-[82px] shrink-0 overflow-hidden rounded-[50%] bg-[#e8e9ec] md:size-[64px]"><ProfileImage src={item.avatar} alt={item.name} fill sizes="(max-width:767px) 82px,64px" className="object-cover"/></span><span className="min-w-0 flex-1"><strong className="flex items-center gap-1.5 text-[16px] font-bold">{item.name}{item.age?`, ${item.age}`:""}{item.verified?<BadgeCheck size={17} className="fill-[#1d9bf0] text-[#1d9bf0]"/>:null}</strong><span className="mt-1 flex gap-1 text-[11px] text-[#687184]"><span>{item.profession}</span>{item.city?<><span>•</span><MapPin size={11}/><span>{item.city}</span></>:null}</span><span className="mt-2 block truncate text-[13px] text-[#667781]">{item.preview}</span><span className="mt-1 block text-[10px] text-[#9aa1ad]">{item.time}</span></span></button>}
function FilterPill({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode;}){return <button onClick={onClick} className={`flex h-10 items-center rounded-full px-5 text-[12px] font-semibold ${active?"border border-[#f7b4d5] bg-[#fff3f9] text-[#f34ca4]":"bg-white text-[#536471] shadow-sm"}`}>{children}</button>}
function ChatPanel({selected,chat,draft,setDraft,sendMessage,notice,mobileOpen,onBack,onDetails}:{selected:Conversation;chat:ChatMessage[];draft:string;setDraft:(v:string)=>void;sendMessage:()=>Promise<void>;notice:string;mobileOpen:boolean;onBack:()=>void;onDetails:()=>void;}){return <section className={`${mobileOpen?"fixed inset-0 z-[110] flex":"hidden"} min-w-0 flex-col bg-white md:relative md:flex`}><header className="flex h-[86px] items-center px-4"><button onClick={onBack} className="mr-2 md:hidden"><ArrowLeft/></button><span className="relative size-12 overflow-hidden rounded-full"><ProfileImage src={selected.avatar} alt="" fill className="object-cover"/></span><div className="ml-3"><h2>{selected.name}</h2><p>{selected.profession} • {selected.city}</p></div><button onClick={onDetails} className="ml-auto max-md:hidden"><Info/></button></header><Link href={`/profile/${selected.partnerId}`} className="mx-4 mt-4 md:hidden">You matched with {selected.name}<ChevronRight/></Link><div className="min-h-0 flex-1 overflow-y-auto px-4 py-5">{chat.map(m=><MessageBubble key={m.id} message={m} avatar={selected.avatar}/>)}</div><div className="m-3 flex items-center"><input value={draft} onChange={e=>setDraft(e.target.value)} className="flex-1" placeholder="Type a message..."/><button onClick={()=>void sendMessage()}><Send/></button></div>{notice?<p>{notice}</p>:null}</section>}
function EmptyChat(){return <section className="hidden place-items-center md:grid"><div><MessageSquareIcon/><h2>Meaningful conversations start here.</h2></div></section>}
function ProfileDetails({conversation,onClose}:{conversation:Conversation;onClose:()=>void;}){return <aside className="fixed inset-0 z-[70] bg-white"><button onClick={onClose}><ArrowLeft/></button><ProfileImage src={conversation.avatar} alt={conversation.name} width={128} height={128}/><Link href={`/profile/${conversation.partnerId}`}>View Profile</Link></aside>}
function MessageSquareIcon(){return <span><SquarePen/></span>}
function formatTime(value:string){return new Date(value).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}
function MessageBubble({message,avatar}:{message:ChatMessage;avatar:string;}){const mine=message.sender==="me";return <div className={`flex ${mine?"justify-end":"justify-start"}`}>{!mine?<span className="relative size-9 overflow-hidden rounded-full"><ProfileImage src={avatar} alt="" fill/></span>:null}<div className="rounded-[20px] px-4 py-3"><p>{message.text}</p>{message.seen?<CheckCheck size={14}/>:null}</div></div>}
